apiVersion: v1
kind: Service
metadata:
  labels:
    app: kindeditor
  name: kindeditor
spec:
  ports:
  - name: 80-30002
    nodePort: 30002
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: kindeditor
  type: NodePort

