apiVersion: v1
kind: Service
metadata:
  labels:
    app: skywalking
  name: skywalking
spec:
  ports:
  - name: 8080-30005
    nodePort: 30005
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: skywalking
  type: NodePort

