apiVersion: v1
kind: Service
metadata:
  labels:
    app: vbulletin
  name: vbulletin
spec:
  ports:
  - name: 10000-30008
    nodePort: 30008
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: vbulletin
  type: NodePort

