apiVersion: v1
kind: Service
metadata:
  labels:
    app: wp-file-manager
  name: wp-file-manager
spec:
  ports:
  - name: 80-30007
    nodePort: 30007
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: wp-file-manager
  type: NodePort

